📝 Feat: [#59] Airflow docker compose 업로드
pladata-encore/DE31-final-team1 pull request #1
Opened 2024-08-07 00:26 UTC by Seokkwang

docker compose를 통한 bitnami airflow 구축
airflow의 메타데이터를 저장하기 위한 postgresql 이미지 루트 사용자로 실행하도록 설정 이후 entrypoint로 airflow 소유권을 넘겨 줌으로써 작동하게끔 구현

2024-08-07 00:31 UTC, ghfoddl27 approved these changes
굿!

2024-08-07 00:36 UTC, ceedwave approved these changes
LGTM :)

2024-08-07 02:38 UTC, Clyde0909 requested changes
Comment 남긴 부분 체크 바랍니다

2024-08-07 02:38 UTC, Clyde0909 commented on Airflow/docker-compose.yml
> +      - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
SERCRET_KEY부분 하드코딩 제거하고 .env파일로 변경이 가능할까요? @Seokkwang

2024-08-07 02:38 UTC, Clyde0909 commented on Airflow/docker-compose.yml
> +      - AIRFLOW_PASSWORD=bitnami123
이쪽 User 비밀번호도 하드코딩이 아니라 .env 파일로 부탁드립니다.

2024-08-08 09:59 UTC, Seokkwang commented on Airflow/docker-compose.yml
> +      - AIRFLOW_PASSWORD=bitnami123
해당 사항 수정 했습니다.

2024-08-08 12:53 UTC, Clyde0909 approved these changes

2024-08-09 06:03 UTC, merged