Feat [#146] flask_nifi_mysql 연결
pladata-encore/DE31-final-team1 pull request #29
Opened 2024-08-30 06:42 UTC by jotaesik

flask-nifi api 연동
기존에 있던 user 테이블에 user별 process_group_id 추가

2024-08-30 06:42 UTC, ceedwave approved these changes
감사합니다.

2024-09-02 03:23 UTC, Clyde0909 approved these changes
LGTM

2024-09-04 00:35 UTC, Clyde0909 commented on .env
.env 파일 ignore 처리하고 Git에 track되지 않게 관리해주세요

2024-09-04 00:37 UTC, Clyde0909 commented on BE/app/v1/nifi/nifi_api.py
해당 파일에도 몽고DB Credential 그대로 나와있는데 .env통해서 읽는걸로 수정 부탁드립니다.

2024-09-04 00:38 UTC, Clyde0909 requested changes
코멘트 남긴 파일들 수정 바랍니다.

2024-09-05 03:50 UTC, Clyde0909 approved these changes
LGTM

2024-09-05 03:57 UTC, merged