Feat: [#169] flask-nifi-be
pladata-encore/DE31-final-team1 pull request #53
Opened 2024-09-11 05:57 UTC by jotaesik

nifi 초기화(기존 생성된 default 그룹 전부삭제)
완성된 consumekafka 생성 api추가

2024-09-12 01:37 UTC, Clyde0909 requested changes
코멘트 부분 검토 바랍니다.

2024-09-12 01:37 UTC, Clyde0909 commented on BE/app/v1/nifi/nifi_api.py
> +    # user_process_group_id = await get_user_process_group_id(152)
로그인 유저에 따라 동적으로 쿼리하는 기능 구현 바랍니다.

2024-09-12 01:37 UTC, Clyde0909 commented on BE/docker-compose.yaml
> +      - /home/dp/nifi_be4/DE31-final-team1/BE:/home/mydir/api-server
상대경로로 작성 가능한지 여부도 체크 바랍니다.
최종 배포환경은 로컬 클러스터가 아닌 EC2 인스턴스입니다.

2024-09-19 03:22 UTC, jotaesik commented on BE/docker-compose.yaml
> +      - /home/dp/nifi_be4/DE31-final-team1/BE:/home/mydir/api-server
넵 ec2 할때 하겠습니다

2024-09-23 00:50 UTC, jotaesik commented on BE/app/v1/nifi/nifi_api.py
> +    # user_process_group_id = await get_user_process_group_id(152)
새롭게 develop에서 branch 따서 하겠습니다!

2024-09-23 07:18 UTC, jotaesik commented on BE/app/v1/nifi/nifi_api.py
> +    # user_process_group_id = await get_user_process_group_id(152)
새롭게 #184번에 따서 했습니다

2024-09-23 07:19 UTC, jotaesik commented on BE/docker-compose.yaml
> +      - /home/dp/nifi_be4/DE31-final-team1/BE:/home/mydir/api-server
새롭게 브랜치따서 했기에 저 부분 해결했습니다

2024-09-23 07:26 UTC, closed without merging