Feature/if #29 docker-file,dockercompose 작성
pladata-encore/DE31-final-team1 pull request #8
Opened 2024-08-12 06:23 UTC by jotaesik

dp5에 구성하는데 필요한 docker파일들과
settings 파일을 nifi에 구성하였습니다

2024-08-12 06:33 UTC, Seokkwang commented on NiFi/docker-compose.yaml
> +      - SINGLE_USER_CREDENTIALS_USERNAME=admin
하드코딩 말고 .env 파일로 만들어주실수 있을까요

2024-08-12 06:35 UTC, Seokkwang requested changes

2024-08-12 06:35 UTC, Seokkwang commented on NiFi/docker-compose.yaml
> +      - SINGLE_USER_CREDENTIALS_PASSWORD=admin_password
하드코딩 말고 .env 파일로 만들어주실수 있을까요

2024-08-13 02:26 UTC, ceedwave approved these changes
LGTM

2024-08-29 02:33 UTC, ghfoddl27 approved these changes
굿!

2024-08-29 02:46 UTC, Clyde0909 commented on NiFi/docker-compose.yaml
> +      - SINGLE_USER_CREDENTIALS_PASSWORD=admin_password
commit [c93929b](https://github.com/pladata-encore/DE31-final-team1/pull/8/commits/c93929b16d4010d8a1de8385e44024c52ca32ef0) 에 의해 수정됨

2024-08-30 01:21 UTC, Seokkwang approved these changes

2024-08-30 01:21 UTC, merged